### ISSUE TITLE
deployments with multiple endpoints get all traffic routed to first port

### ISSUE THREAD

**Issue by metskem-rabo** [magneticio/vamp-core#12]
I am trying to deploy an application with 2 endpoints (simple dropwizard with an extra adminport).
I want both ports to be accessible from the outside (a url to the router).

I use the following blueprint:
```
name: depl-dropwizard-01
endpoints:
  rabo-test-cluster.dummyref: '19081'
  rabo-test-cluster.adminport: '19082'
clusters:
  rabo-test-cluster:
    services:
    - breed:
        name: breed-test-app1
        deployable: cmd://dropwizardtest-1.1-SNAPSHOT/start.sh
        ports:
          dummyref: 9999/http
          adminport: 9082/http
        environment_variables:
          DW_LOGLEVEL: info
          DW_JDBC_URL: jdbc:mysql://lsrv4180.linux.rabobank.nl/dropwizardtest
          PORT1: '9082'
      scale:
        cpu: 0.1
        memory: 256.0
        instances: 2
      dialects:
        marathon:
          uris:
          - http://lsrv5270.linux.rabobank.nl/vamp/artifacts/dropwizardtest-assembly.zip
          constraints:
          - - stage
            - LIKE
            - test
          - - hostname
            - UNIQUE
```

My assumption is that traffic on port 19082 would go to the application's port 9082.
However, this traffic gets directed to application's port 9081.

Here is the relevant portion of the output of a REST call to v1/routes : 

```
    {
        "name": "577009b1-6832-4db1-9209-b9049b12bb08_19081",
        "port": 19081,
        "protocol": "tcp",
        "httpQuota": {},
        "tcpQuota": {},
        "filters": [],
        "services": [
            {
                "name": "rabo-test-cluster.ports.dummyref",
                "weight": 100,
                "servers": [
                    {
                        "name": "577009b1-6832-4db1-9209-b9049b12bb08_19081",
                        "host": "lsrv5269.linux.rabobank.nl",
                        "port": 33012
                    }
                ]
            }
        ]
    },
    {
        "name": "577009b1-6832-4db1-9209-b9049b12bb08_19082",
        "port": 19082,
        "protocol": "tcp",
        "httpQuota": {},
        "tcpQuota": {},
        "filters": [],
        "services": [
            {
                "name": "rabo-test-cluster.ports.adminport",
                "weight": 100,
                "servers": [
                    {
                        "name": "577009b1-6832-4db1-9209-b9049b12bb08_19082",
                        "host": "lsrv5269.linux.rabobank.nl",
                        "port": 33013
                    }
                ]
            }
        ]
    },
    {
        "name": "577009b1-6832-4db1-9209-b9049b12bb08_rabo-test-cluster_9999",
        "port": 33012,
        "protocol": "http",
        "httpQuota": {},
        "tcpQuota": {},
        "filters": [],
        "services": [
            {
                "name": "breed-test-app1",
                "weight": 100,
                "servers": [
                    {
                        "name": "867777eb539f647f076a016250a4cf2539bd641a",
                        "host": "lsrv5260.linux.rabobank.nl",
                        "port": 31938
                    },
                    {
                        "name": "e91d279e646b5e8e41b354c16c82cf88ade8386",
                        "host": "lsrv5259.linux.rabobank.nl",
                        "port": 31926
                    }
                ]
            }
        ]
    },
    {
        "name": "577009b1-6832-4db1-9209-b9049b12bb08_rabo-test-cluster_9082",
        "port": 33013,
        "protocol": "http",
        "httpQuota": {},
        "tcpQuota": {},
        "filters": [],
        "services": [
            {
                "name": "breed-test-app1",
                "weight": 100,
                "servers": [
                    {
                        "name": "867777eb539f647f076a016250a4cf2539bd641a",
                        "host": "lsrv5260.linux.rabobank.nl",
                        "port": 31938
                    },
                    {
                        "name": "e91d279e646b5e8e41b354c16c82cf88ade8386",
                        "host": "lsrv5259.linux.rabobank.nl",
                        "port": 31926
                    }
                ]
            }
        ]
    }
]
```

The set of servers for rabo-test-cluster_9999 is the same as for rabo-test-cluster_9082, while they should have had different ports.
