### ISSUE TITLE
Posting bleuprint to deployment results in endless vamp-router updates and unfinished services state

### ISSUE THREAD

**Issue by tnolet** [magneticio/vamp-core#4]
POSTing this blueprint to the `/deployments` endpoint results in Core endlessly trying to update Vamp-router and reporting in the `state` field `"ReadyForDeployment"` although the container is deployed and Router is in the correct state:
```yaml
name: wordpress

endpoints:
  wordpress.ports.port: 9050
#parameters:
#  wordpress.ports.port: 80
#  wordpress.environment_variables.test: 8080

clusters:

  wordpress:
    breed:
      name: wordpress
      deployable: tutum/wordpress
      ports:
        name: port
        direction: OUT
        value: 80

    scale:
      cpu: 1
      memory: 1024
      instances: 2
    
    routing:
      filters:
        - condition: user-agent = ios

    sla:
      type: response_time_sliding_window
      threshold:
        upper: 1000
        lower: 100
      window:
        interval: 600
        cooldown: 600
      escalations:
        - 
          type: scale_instances
          minimum: 1
          maximum: 3
          scale_by: 1
```
